from enum import Enum

class PropertyField(str, Enum):
    """属性字段常量枚举"""
    # 基础类型
    INT_PROPS = "IntProps"
    BOOL_PROPS = "BoolProps" 
    DOUBLE_PROPS = "DoubleProps"
    STRING_PROPS = "StringProps"
    OBJECT_PROPS = "ObjectProps"
    # SPT独特类型
    XYZ_PROPS = "XYZProps"
    COLOR_PROPS = "ColorProps"
    PREFAB_PROPS = "PrefabProps"
    MONGO_ID_PROPS = "MongoIdProps"
    LOOT_RARITIES = "LootRarities"
    RELOAD_MODE_PROPS = "ReloadModeProps"
    GRID_PROPS = "GridProps"
    SLOT_PROPS = "SlotProps"
    JSON_ELEMENT_PROPS = "JsonElementProps"
    THROW_WEAP_TYPE_PROPS = "ThrowWeapTypeProps"
    ARMOR_MATERIAL_PROPS = "ArmorMaterialProps"
    STACK_SLOT_PROPS = "StackSlotProps"
    ITEM_DROP_SOUND_TYPE_PROPS = "ItemDropSoundTypeProps"
    ENUMERABLE_STRING_PROPS = "EnumerableStringProps"
    DICTIONARY_PROPS = "DictionaryProps"
    ENUMERABLE_MONGO_ID_PROPS = "EnumerableMongoIdProps"
    WEAPON_RECOIL_SETTINGS_PROPS = "WeaponRecoilSettingsProps"
    PLAYER_SIDE_MASK_PROPS = "PlayerSideMaskProps"
    EQUIPMENT_SLOTS_PROPS = "EquipmentSlotsProps"
    NESTED_DOUBLE_LIST_PROPS = "NestedDoubleListProps"
    SHOTS_GROUP_SETTINGS_PROPS = "ShotsGroupSettingsProps"
    REPAIR_STRATEGY_TYPE_PROPS = "RepairStrategyTypeProps"
    HEALTH_FACTOR_DICTIONARY_PROPS = "HealthFactorDictionaryProps"
    DAMAGE_EFFECT_TYPE_DICTIONARY_PROPS = "DamageEffectTypeDictionaryProps"